### ISSUE TITLE
Add a Security and Privacy considerations section to the explainer

### ISSUE THREAD

**Issue by raymeskhoury** [WICG/file-handling#17]
Notes:
1. Should the app be automatically registered as a file handler with the OS upon installation or should there be a separate permission (my preference, feel free to disagree: automatic)
2. Should the app be automatically registered as the **default** handler for a file type with the OS upon installation (my preference: no, instead the app has to ask the user to register as the default handler)
3. If the user opens a file in the app, should they need to request read permission (my preference: no, it should behave the same as if choosing the via the file picker)
4. If the user opens a file in the app, should they need to request write permission (my preference: no since this matches user expectations in the OS)

@mkruisselbrink @inexorabletash

**Comment by fallaciousreasoning** [comment]
1. I think I agree.
2. More wary here, can we do this on all operating systems? Could we add a checkbox at install time?
3. Definitely prefer no read permission prompt, I think it's implicitly being granted by attempting to open in the app.
4. Write permission prompt: I think I'd prefer no, but I could be convinced otherwise.

**Comment by fallaciousreasoning** [comment]
A security and privacy section was added as part of #19
