### ISSUE TITLE
File Association Images

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/file-handling#24]
It's common on existing operating systems for the application to provide an image representing the file type. Maybe we should provide some mechanism for doing this?

![File icons from Microsoft Office](https://user-images.githubusercontent.com/7678024/62261929-3faefe00-b45a-11e9-827e-b7a9624e27f2.png)

> File icons from Microsoft Office

This is probably low priority, and can likely be tacked on later. In the meantime we can use an app icon from the manifest.

Possibly, we could solve this with some more entries in the manifest's [icons](https://www.w3.org/TR/appmanifest/#icons-member), or by adding a new property to the file handlers:

```json
{
    "file_handler": {
        "action": "/open-files",
        "files": [
             {
                 "name": "csv",
                 "accepts": [ ".csv", "text/csv" ],
                 "icons": [
                      { "src": "https://.../my-icon.png", "sizes": "256x256" }
                 ]
             }
        ]
    }
}
```

@mgiuca, any thoughts?

**Comment by mgiuca** [comment]
Agreed, this would be nice.

Adding a new set of ImageResources to the file_handler makes the most sense (if we allow multiple file handlers) (as opposed to a new purpose): there is a 1:1 mapping from file_handler to icon, rather than from app to icon.

There's a potential phishing type of attack here where we allow apps to make an icon that looks like MS Word and then you double-click on it and you think you're using Word but it's actually a web thing that steals your data. So we'll have to think about that. In the mean time, badging a white page with the app's icon (or something that the user agent can decide to do unilaterally) makes sense.

This is yet more fuel to the argument that we should have multiple _file handlers_ with one list of MIME types each, as opposed to one file handler with multiple "fileses".

```json
{
  "file_handlers": [
    {
      "name": "csv",
      "action": "/open-files",
      "accepts": [ ".csv", "text/csv" ],
      "icons": [
        { "src": "https://.../my-icon.png", "sizes": "256x256" }
      ]
    }
  ]
}
```

**Comment by fallaciousreasoning** [comment]
I'm getting pretty convinced about having multiple *file handlers* too. Want to add a comment on #7? We can update the explainer/API and close that issue, as we seem to have decided that, yes, they are necessary, but we need to change the shape of the current API a bit.

My one lingering doubt here is that we're no longer going to look the same as [Web Share Target Files](https://github.com/WICG/web-share-target/blob/master/docs/explainer.md#manifestwebmanifest) but I think I can live with it (they solve quite different problems, but consistency would've been nice).

**Comment by dway123** [comment]
I've written a design document to discuss how this might be implemented (in Chrome), and some relevant security/privacy considerations, at https://docs.google.com/document/d/1OAkCvMwTVAf5KuHHDgAeCA3YwcTg_XmujZ7ENYq01ws/edit#

**Comment by fallaciousreasoning** [comment]
It looks pretty cool to me! I'm glad this is still being worked on :) I left a few comments on the document but I don't know how useful they'll be (I'm pretty out of the loop, and I don't work on specs any more).

**Comment by mgiuca** [comment]
Assigning @dway123 who is deep in the design for this.

Please also note the discussion [here](https://github.com/WICG/file-handling/issues/7#issuecomment-559663615) which is pertinent.

**Comment by dway123** [comment]
I think the explainer now mentions this to some degree, since [this commit](https://github.com/WICG/file-handling/commit/1a9196a7799ffe24ba1dd62bd912b388e02c40aa). Therefore, I think this issue can now be closed.

Note that this isn't implemented in any browser implementation yet, but we're working on this in Chrome.
