### ISSUE TITLE
Should applications be able to specify the meaning of a MimeType?

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/file-handling#26]
If an application on Linux wants to register a custom file extension, they must also register a custom mime type (Linux file handlers only work on mimetypes). 

The current syntax provides no easy way to specify this mapping. We could implement this by changing the `accept` entry to be a dictionary:

so this:
```json
{
  "name": "Grafr",
  "file_handler": [
    {
      "name": "Grafr Files",
      "accept": [".grafr", "application/vnd.grafr.graph", ".graph", "text/svg+xml", ".svg" ]
    }
  ]
}
```

would become:
```json
{
  "name": "Grafr",
  "file_handler": [
    {
      "name": "any",
      "accept": {
        "application/vnd.grafr.graph": [ ".grafr", ".graph" ],
        "text/svg+xml": [ ".svg" ]
      }
    }
  ]
}
```

Note that the first syntax is ambiguous and we can't infer what extensions are related to the "application/vnd.grafr.graph" mimetype, while the second explicitly lays out the relationship. 

@mgiuca

**Comment by mgiuca** [comment]
Seems pretty nice.

I know some web folks really object to the concept of file extensions permeating into the web platform, since they're "unwebby" (perhaps DOSsy?), and this might cross a line since now instead of merely _allowing_ extensions we're making them essentially mandatory.

But I think the case is: they _are_ part of reality ([Windows drive letters](https://url.spec.whatwg.org/#windows-drive-letter), anyone?), some systems including Windows can only match against file extensions so anybody who is just using MIME types is going to make their app unusable on Windows. Similarly, anybody who is just using file extensions is going to make their app unusable on other platforms (maybe Linux, unless we custom-register a MIME type).

So I like this.

**Comment by fallaciousreasoning** [comment]
All right, I'll throw together a PR for this.
