### ISSUE TITLE
Consider allowing drive-by web to access this API

### ISSUE THREAD

**Issue by dway123** [WICG/file-handling#47]
File Handling should have a definitive user interaction and strong signal of trust. Currently, installation of of the web application is listed as a signal of this trust, as installed applications on host operating systems generally already have access to permissions similar to this API (but generally a bit more powerful/dangerous).

We should consider allowing the drive-by web to access this API as well, most likely in a future iteration of this proposal. A potential way to expose this, is to have a
> "open with a web application" option for the drive-by web, which would cause chrome to pop up some list of all websites you've visited recently [...] that could handle that file type ([src](https://github.com/WICG/file-handling/pull/46#discussion_r541307911))

Such a implementation could allow many more sites who prefer not to be installed, to have access to this API. That said, they certainly might not like this approach, as it would require an extra UX step for the user to access the API (Having a browser "open with a web application" option, then selecting their web application afterwards), as well as reduced association with that application (as the web application name/logo wouldn't be visible directly from the underlying operating system).

This would also make File Handling more consistent with the related launch events API, which [only recommends / doesn't strictly require installation](https://github.com/WICG/sw-launch/blob/master/explainer.md#restricting-launch-events-to-installed-websites).

Surfaced in https://github.com/WICG/file-handling/pull/46#discussion_r540670121

**Comment by mgiuca** [comment]
Continuing on from that thread in #46: I note that @fallaciousreasoning raised this as a matter of consistency with Launch Events, not because it's something he necessarily wanted:

> Yeah, honestly it seems way more sensible to only expose this to installed web applications at first. I was mostly just interested from a consistency point of view.

So on the consistency note, I agree. File Handling and Launch Event are very closely related and should be exposed in the same context. The two explainers could be updated to be more consistent, but note that Launch Event does merely say "recommended". Note that neither of these are "specs". When there's a formal spec, we'll be more careful about the language.

In the W3C spec side of things, there is no way to mandate this one way or another. We try to keep UI decisions open for browser manufacturers to make policy decisions as they see fit. Web Share Target provides a concrete example of this: [§4 Registration of web share targets](https://w3c.github.io/web-share-target/#registration-of-web-share-targets):

> How and when web share targets are "registered" is at the discretion of the user agent and/or the end user. In fact, "registration" is a user-agent-specific concept that is not formally defined here; user agents are NOT REQUIRED to "register" web share targets at all; they are only REQUIRED to provide some mechanism to convey shared data to a web share target of the end user's choosing. User agents MAY consider a web share target "registered" even if it is not installed.
>
> The user agent MAY automatically register all web share targets as the user visits the site, but it is RECOMMENDED that more discretion is applied, to avoid overwhelming the user with the choice of a large number of targets.

Note that the language there is very open to allowing browsers to register targets based on any signal, whether it be installation, engagement, some other explicit user action that isn't install, etc. It isn't the spec's job to mandate how sites are registered. I think both File Handlers and Launch Event / Link Capturing will want to basically say the same thing as Web Share Target.

**On the other hand**, when we're talking about the actual policy that a browser (e.g., Google Chrome) should enact, I strongly believe we should tie all of these with installation. As a user, I don't want to have random websites I've visited popping up in my share sheet, "open with" lists, and automatically capturing links in a window. Installation is the primary signal a user gives us that they are interested in having the site remain present on their device when the tab isn't open. It's much simpler to tie all of these "persistence" features to install, rather than giving the user separate choices to register file handlers, share targets, etc. The current exception to this is protocol handlers, which can be separately registered using in-browser UI. That has historical reasons (protocol handlers predate installation by several years), and I believe if we were designing it today, we would also tie it with installation (and in fact there's a [proposal in that direction](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/URLProtocolHandler/explainer.md)).

This isn't relevant to the spec discussion, but when it comes to the actual implementation in Chrome, I will be arguing that we tie these to installation.

**Comment by fallaciousreasoning** [comment]
Yeah sorry for the confusion, but yeah, like @mgiuca says :) We can't mandate what actual browsers do with regard to their UI in a spec, but for a specific vendor's policy it makes complete sense to gate this behind installation.

**Comment by dway123** [comment]
Thank you for clarifying, and particularly for the note between specification and explainer language (as well as user agent implementation details). Yes, in this case, I agree that the explainer should recommend installation, the specification can mention installation as an option for registration, and the Chromium implementation should require installation.
