### ISSUE TITLE
Rules for mime types

### ISSUE THREAD

**Issue by evanstade** [WICG/file-handling#67]
The explainer says:

> if the web application accepts all text and image formats that the browser supports, "text/*" and "image/*" could be used, i.e. "*" may appear in place of a subtype. "*/*" can be used if all files are accepted. 

However I'm not sure this actually works in Chrome, on all OSes, or that we want it to work.

There's also no explanation of what constitutes a valid mime type, although this is defined in rfc6838: https://datatracker.ietf.org/doc/html/rfc6838#section-4.2

**Comment by Offroaders123** [comment]
I came across this too, and it does seem to be inconsistent across platforms. On Chrome OS, setting a mime type of `"text/*"` seems to work with all text files, but specifying a list of extension types, like `[".txt",".html",".css",".js"]`, only seem to work on Windows and macOS. I think it would be great if the Chrome OS functionality could come to the other major platforms, but I'm wondering if this is an implementation limitation. Maybe Chromium could work around this? It may be too big a problem to solve though.

**Comment by fallaciousreasoning** [comment]
> I came across this too, and it does seem to be inconsistent across platforms. On Chrome OS, setting a mime type of "text/*" seems to work with all text files, but specifying a list of extension types, like [".txt",".html",".css",".js"], only seem to work on Windows and macOS. I think it would be great if the Chrome OS functionality could come to the other major platforms, but I'm wondering if this is an implementation limitation. Maybe the Chromium codebase could work around this? It may be too big a problem to solve though.

The reason for this is that different OSs support different ways of specifying file types. On Windows, and MacOS, for instance, it is only possible to specify a file extension to set a handler (i.e. `.txt`, `.html` ect). However, on Linux, file handlers can only be setup via a mimetype (text/plain). 

Because file handlers should work on all operating systems, and because we don't want user agents to be responsible for maintaining a file type / mime mapping for all mimetypes we require applications to specify which mimetypes they support **AND** which file extensions they support.

> However I'm not sure this actually works in Chrome, on all OSes, or that we want it to work.

Whether this proposal should support wildcard mimetypes is a different story, which I don't know if I have an opinion on 😆 Perhaps not if some platforms don't support it, as it would force developers to specify the specific mimetypes as well as the wildcard to maximise what they can handle (although it does sound like this works on ChromeOS, based on @Offroaders123's comment).

**DISCLAIMER**
I was the one originally behind this proposal, but I don't work on this any more so take my opinions with several large grains of salt.

**Comment by Offroaders123** [comment]
Being less of an implementation issue, and more of a DX one, is there a nice way to find common extensions you'd like to support, where wildcard selectors aren't supported? By this, I mean is there anything like an online directory of all `text/*` extensions that I could use for a refresher? It isn't that big of a deal to try to think of different types I may want my program to open with, but it seems harder to predict other users' less-common use cases. I can think of a good amount off of the top of my head, but there are a lot of unique `text/*` extensions that I may never have heard of before, that someone else might hope to open my program with.

I mostly am looking for a similar ease-of-use that comes with using VS Code, it seems like almost any plain text file I have has an option to open with VS Code. Would their team have used a list they used to decide which files to associate with? I'm just curious how I can have an extensive list too.

Sorry for the long message 😬

**Comment by fallaciousreasoning** [comment]
I'm not sure. I found [this](http://dotwhat.net/type/text-files) with a little bit of searching. You could probably have a look at the VSCode source and try and find which associations it sets by default.

**Comment by mkruisselbrink** [comment]
FWIW, the File System Access API (which uses the same format to specify allowed mime types and file extensions) does try to map mime types to file extensions on all platforms. I think that only works (for wildcard mime types at least) for types that are hard coded in chrome's internal mime type lists. For non-wildcard mime types that might also look at what the operating system knows about (but that then of course means that the actual behavior depends on what happens to be registered with the OS).

**Comment by evanstade** [comment]
I've updated the spec to specify that MIME type is necessary (e.g. for Linux) but not sufficient (e.g. for Windows).
